### ISSUE TITLE
Week 6 ready for review

### ISSUE THREAD

**Issue by dmueller3** [dmueller3/FantasyFootballScheduler#2]
@pawaitemadisoncollege week 6 is complete

![image](https://github.com/user-attachments/assets/d74c09e1-95b2-4bd9-b9f4-1bf43b0b603b)

http://fantasy-football-scheduler-env.eba-9tpd7jsa.us-east-2.elasticbeanstalk.com/

**What were your key learning points/takeaways?**
I can deploy my database to AWS and access it from intellij

**What challenged you?**
I initially could not access my AWS database data, and had inexplicable errors.

What problems did you solve and what resources did you use to solve them?
I went on google, and found a stackoverflow article that helped me. I can't use special characters in my password.
https://stackoverflow.com/questions/47701704/elastic-beanstalk-application-cant-connect-to-database-but-server-can

**Comment by pawaitemadisoncollege** [comment]
It's great to see your indie project out on the web already @dmueller3! This sets you up really well for checkpoint 2. Way to go!
