### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by mollymccarthy03** [dmueller3/FantasyFootballScheduler#3]
# Design/Code Review 1

### Reviewer: Molly McCarthy @mollymccarthy03

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Love your problem statement! Easy to follow, even for someone who doesn't get fantasy football! I'd suggest adding that it isn't a bracket style, and more of a time scheduler. This may be obvious but I didn't really know what to expect. Maybe it would be worthwhile to add another character that isn't familiar with fantasy football scheduling at all?|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |  I really liked your design, I think its going to look really clean. Maybe to elevate it, it could be good to go back in with pencil to map out containers or indicate which things are clickable. It would be interesting to see what colors you will pick! All layouts were logical and looked great. One thing I should have asked during our meeting was what the "Regen" button stands for on the schedule results. Would this just bring you back to create a new schedule or shuffle the weekly answers/pairings around? Maybe this would be good to divide into two different buttons?|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Everything was demonstrated well! I might think about implementing delete schedule with launch? It could be a nice thing for users to have, espically if they will be able to see their history, and it would be fairly easy to add to the DAO. One team can be part of many schedules is a great one to many relationship, and I'm interested to see how you will implement this further when building the generation of the schedules. Are schedules unlimited since they are generated? |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.  7. No sensitive information is visible in the repository (secrets, passwords, etc). | Everything was looking great, and it was so nice to see your code out on the web! JSP code looked nice! I'd say just keep up the great organization that you've got going now! I am excited to see what other things you could implement into this project.|

**Comment by pawaitemadisoncollege** [comment]
@mollymccarthy03 Thanks for your review of @dmueller3 's project so far. Your feedback shows you took a careful look at the project to-date and struck a nice balance between kudos and areas for improvement/questions.
